### ISSUE TITLE
음료 사진 수집

### ISSUE THREAD

**Issue by pers0n4** [GDSC-DEU/2022-SolutionChallenge-CanDrink#1]
음료 구별을 위한 학습 데이터를 수집해야 합니다.

## 논의 사항

- 어떤 음료 사진을 수집할 건지?
- 몇 장 정도 수집하면 적절할지?
- 처음에 몇 개 정도 판별해볼 것인지?

**Comment by solo5star** [comment]
* 수집할 캔 음료 사진
  - 코카콜라
  - 펩시
  - 스프라이트
* 종류 당 300장 수집
