### ISSUE TITLE
지속적인 진동 피드백 구현

### ISSUE THREAD

**Issue by SerenityS** [GDSC-DEU/2022-SolutionChallenge-CanDrink#14]
## 참고 링크
- [flutter_vibrate](https://pub.dev/packages/flutter_vibrate)

## Spec
- 음료 인식이 안되었을 때: 1초마다 약하게 진동
- 음료 인식은 되었는데 어떤 음료일지 모를 때: 0.5초마다 중간 진동
- 음료 인식 성공 시: 0.2초마다 세게 진동

**Comment by solo5star** [comment]
## 진동 패턴
* 음료 인식이 안되었을 때: 1초마다 약하게 진동
* 음료 인식 성공 시: 강하게 진동
